services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  service-registry:
    build: ./service-registry
    image: service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  config-server:
    build: ./springboot-cloud-config-server
    image: config-server
    container_name: config-server
    ports:
      - "9196:9196"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9196/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      service-registry:
        condition: service_healthy

  cloud-gateway:
    build: ./cloud-gateway
    image: cloud-gateway
    container_name: cloud-gateway
    ports:
      - "8080:8080"
    environment:
      CONFIG_SERVER_URL: http://config-server:9196
    depends_on:
      config-server:
        condition: service_healthy

  security-service:
    build: ./security-service
    image: security-service
    container_name: security-service
    ports:
      - "8089:8089"
    environment:
      CONFIG_SERVER_URL: http://config-server:9196
      DB_URL: jdbc:mysql://mysql:3306/microservices
    depends_on:
      config-server:
        condition: service_healthy
      mysql:
        condition: service_healthy

  order-service:
    build: ./order-service
    image: order-service
    container_name: order-service
    ports:
      - "9192:9192"
    environment:
      CONFIG_SERVER_URL: http://config-server:9196
    depends_on:
      config-server:
        condition: service_healthy

  payment-service:
    build: ./payment-service
    image: payment-service
    container_name: payment-service
    ports:
      - "9191:9191"
    environment:
      CONFIG_SERVER_URL: http://config-server:9196
    depends_on:
      config-server:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"     # exposes MySQL to localhost
    environment:
      MYSQL_ROOT_PASSWORD: Abc@12345
      MYSQL_DATABASE: microservices
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      service-registry:
        condition: service_healthy

volumes:
  mysql_data: