services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - internal

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - internal

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.2
    container_name: filebeat
    user: root
    command: [ "--strict.perms=false" ]
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - internal
    volumes:
      - ./logs:/logs:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - internal

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - internal
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    networks:
      - internal
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_INTERNAL://:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_INTERNAL://kafka:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "bash", "-c", "nc -z localhost 9093" ]
      interval: 10s
      timeout: 5s
      retries: 10

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    networks:
      - internal
    environment:
      KAFKA_BROKERCONNECT: "kafka:29093"
      JVM_OPTS: "-Xms32M -Xmx64M"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"     # exposes MySQL to localhost
    environment:
      MYSQL_ROOT_PASSWORD: Abc@12345
      MYSQL_DATABASE: security_service_db
    networks:
      - internal
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      service-registry:
        condition: service_healthy

  service-registry:
    build: ./service-registry
    image: service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - internal
    environment:
      ZIPKIN_SERVER_URL: http://zipkin:9411/api/v2/spans
    volumes:
      - ./logs/service-registry:/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  config-server:
    build: ./springboot-cloud-config-server
    image: config-server
    container_name: config-server
    ports:
      - "9196:9196"
    networks:
      - internal
    environment:
      EUREKA_URL: http://service-registry:8761/eureka/
      ZIPKIN_SERVER_URL: http://zipkin:9411/api/v2/spans
    volumes:
      - ./logs/config-server:/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9196/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      service-registry:
        condition: service_healthy

  cloud-gateway:
    build: ./cloud-gateway
    image: cloud-gateway
    container_name: cloud-gateway
    ports:
      - "8080:8080"
    networks:
      - internal
    environment:
      CONFIG_SERVER_URL: http://config-server:9196
      ZIPKIN_SERVER_URL: http://zipkin:9411/api/v2/spans
    volumes:
      - ./logs/cloud-gateway:/logs
    depends_on:
      config-server:
        condition: service_healthy

  security-service:
    build: ./security-service
    image: security-service
    container_name: security-service
    ports:
      - "8089:8089"
    networks:
      - internal
    environment:
      CONFIG_SERVER_URL: http://config-server:9196
      DB_URL: jdbc:mysql://mysql:3306/security_service_db
      ZIPKIN_SERVER_URL: http://zipkin:9411/api/v2/spans
    volumes:
      - ./logs/security-service:/logs
    depends_on:
      config-server:
        condition: service_healthy
      mysql:
        condition: service_healthy

  order-service:
    build: ./order-service
    image: order-service
    container_name: order-service
    ports:
      - "9192:9192"
    networks:
      - internal
    environment:
      CONFIG_SERVER_URL: http://config-server:9196
      KAFKA_BOOTSTRAP_SERVER: kafka:9093
      ZIPKIN_SERVER_URL: http://zipkin:9411/api/v2/spans
    volumes:
      - ./logs/order-service:/logs
    depends_on:
      kafka:
        condition: service_healthy
      config-server:
        condition: service_healthy

  payment-service:
    build: ./payment-service
    image: payment-service
    container_name: payment-service
    ports:
      - "9191:9191"
    networks:
      - internal
    environment:
      CONFIG_SERVER_URL: http://config-server:9196
      ZIPKIN_SERVER_URL: http://zipkin:9411/api/v2/spans
    volumes:
      - ./logs/payment-service:/logs
    depends_on:
      config-server:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    image: notification-service
    container_name: notification-service
    ports:
      - "9193:9193"
    networks:
      - internal
    environment:
      CONFIG_SERVER_URL: http://config-server:9196
      KAFKA_BOOTSTRAP_SERVER: kafka:9093
      ZIPKIN_SERVER_URL: http://zipkin:9411/api/v2/spans
    volumes:
      - ./logs/notification-service:/logs
    depends_on:
      kafka:
        condition: service_healthy
      config-server:
        condition: service_healthy

volumes:
  mysql_data:
  esdata:

networks:
  internal:
    driver: bridge